language: python
python:
- '3.5'
cache: pip
script:
- pytest --json=report.json -v
- echo "Please ignore the following...this is for grading purposes only."
- echo '<MQkrXV>'
- cat report.json
- echo '<MQkrXV>'
